### ISSUE TITLE
Comment reply link

### ISSUE THREAD

**Issue by juweez** [jarednova/timber#319]
Is it possible to add a reply link for comments? 

I've tried doing {{function('comment_reply_link')}} but this doesn't do anything.

**Comment by igregson** [comment]
On a related note, anyone know of a way to add placeholder values to the comment input fields?

**Comment by josephbergdoll** [comment]
@lmartins threaded comments were fixed in the version bump to `0.21.10`, you can get this by pulling `master` or upgrading from the Wordpress backend.

I'll work on implementing a more friendly comment reply link, but I think how it is implemented on view layer should not be determined by Timber itself as there are many factors that go into it — is the comment form injected below the comment? Does it post with AJAX? etc. I think that's still best left to individual theme developers to decide.

**Comment by josephbergdoll** [comment]
Fixed and working in this PR https://github.com/jarednova/timber/pull/708

**Comment by lmartins** [comment]
Thanks @josephbergdoll

**Comment by galaxy-satellite** [comment]
hi there, 
i think that you'll find what you're looking for in this link:
<a href="https://www.galaxy-satellite.com">abonnement iptv</a>

best regards.
