### ISSUE TITLE
TimberImage doesn't resize images on SSL.

### ISSUE THREAD

**Issue by kylehotchkiss** [jarednova/timber#323]
Hey Jared!

I caught a bug with `TimberImage` and `resize()` while the site is running over SSL. I just threw my whole site on SSL because of Google's new recommendation to do that and noticed my resizes didn't work. I turned off SSL to see if my resizes would work again and they did. 

Just from a quick check of the changelog, the issue may have been introduced here: https://github.com/jarednova/timber/releases/tag/0.18.0

Again, thanks for all of your work. I'm a lucky man to work with Wordpress with this elegant platform you've built!

**Comment by georgemandis** [comment]
Also ran into this issue. Tried to find the bug but nothing obvious jumped out at me at glance.

I think it's worth mentioning a possibly easier approach than manually setting WP_CONTENT_URL in your code is to change the WordPress Address URL under Settings > General. For my use-case we were trying to force SSL-everywhere and the original site was entered here with http://.

**Comment by simonmilz** [comment]
After my switch from http to http i simply added this line of code:

```php
add_filter('timber_compile_result', function($output) {
    return str_replace('http://www.domain.de', 'https://www.domain.de', $output);
});
```

and everything works awesome :+1:

**Comment by connorjburton** [comment]
This seems to be down to legacy `http` protocol on images after changing to `https`. Feel free to comment if that's not the case and we can investigate further.

**Comment by simonmilz** [comment]
Okay, thanks for your response. I will comment if i found something else.

**Comment by jancbeck** [comment]
I came across this issue in a recent project. I ended up using this filter, since it should perform a little better than using "timber_compile_result":

```php
add_filter( 'timber/image/new_url', function( $url ){
	if ( is_ssl() ) {
		$url = str_replace( 'http://', 'https://', $url );
	}
	return $url;
} );
```

What's weird about this issue is that I'm using this template code:

```html
{% set header_image = TimberImage(post.get_field('header_image')).src %}
<div class="wrapper"><img class="hero__images-inside" src="{{header_image|resize(0, 381)}}" srcset="{{ header_image|resize(0, 381) }} 1x, {{ header_image|resize(0, 381*2) }} 2x" alt="{{post.title}}" /></div>
```
which got compiled to

<img class="hero__images-inside" src="https://example.com/wp-content/uploads/Abbey_Headshot@2x-0x381-c-default.png" srcset="http://example.com/wp-content/uploads/Abbey_Headshot@2x-0x381-c-default.png 1x, http://example.com/wp-content/uploads/Abbey_Headshot@2x-0x762-c-default.png 2x" alt="Abbey">

As you can see code to generate the first size in the srcset array is identical to the one used in the src attribute, but still got output as http.
