### ISSUE TITLE
get_preview() doesn't resolve [caption] shortcode

### ISSUE THREAD

**Issue by josefvanniekerk** [jarednova/timber#445]
It appears that the .get_preview() Twig function doesn't resolve shortcodes like [caption]

See http://codex.wordpress.org/Caption_Shortcode

I currently have to remove all "Caption" entries from images in my blog, otherwise the shortcode is displayed on the page as is, and not resolved.

Could it be something I'm doing wrong?

**Comment by slimndap** [comment]
Ran into the same issue the other day. Ended up doing it like this:

`{{ function('get_the_excerpt') }}`

**Comment by josefvanniekerk** [comment]
Thanks for the suggestion, tried it as well as the_excerpt(), but both just return nothing.

**Comment by slimndap** [comment]
Make sure you use Timber::query_posts() in your php file. 

—
Slim & Dapper
http://slimndap.com

**Comment by jnweaver** [comment]
Do you have a  excerpt break in your post content?

If so, calling get_preview() will result in the shortcodes not getting parsed (and showing up in your output).

You can get around this by running get_preview() through Wordpress's the_content filter like so:

```
{{ function( 'apply_filters', 'the_content', post.get_preview() ) }}
```

This get_preview() code needs some revisiting. I added the  handler but its implementation is not consistent with other parts of get_preview(), which runs get_content(), applying shortcodes, etc and then trims out the words. If you have a  tag in your content, it does not run through Timber's get_content and trim_words functions (because you've explicitly set the break). But it should probably apply the_content filter. I can revisit this when I have time.

**Comment by josefvanniekerk** [comment]
Managed to get it working. Thanks so much!
