### ISSUE TITLE
get_preview() pulls captions from Jetpack images

### ISSUE THREAD

**Issue by lmartins** [jarednova/timber#517]
When a post opens with a Jetpack image gallery, the `get_preview()` function pulls the captions from those images and show that text in the post preview.

Is there a way to avoid this?

**Comment by lmartins** [comment]
Funny, found my own ticket looking for a solution for this problem.
Anyone found a solution for this

**Comment by jnweaver** [comment]
The easiest solution is to just set an explicit excerpt for the post.

*get_preview* otherwise grabs the data in post_content (tags, shortcodes and all) and runs it through the *the_content* filter. It then strips out tags except for *p a span b i br*. It then trims to the number of words you set and then further strips all tags (by default) or leaves *p a span b i br* tags in place if you set $strip to false. Either way, the text from your gallery caption (or an image caption if your post begins with an image) will come through all of this parsing. I don't think there is a way around this; it's just how get_preview() works. If you set an explicit excerpt on your post, then it bypasses all of the above and allows you greater control.

**Comment by lmartins** [comment]
Totally missed this @jnweaver answer, sorry about that.
Yes, this seems that it's how WordPress does things, so not a Timber issue. Closing.

Thanks for the reply Nick.
