### ISSUE TITLE
Woocommerce product the_content() returns NULL

### ISSUE THREAD

**Issue by lmartins** [jarednova/timber#526]
Im having a few issues with a project, where `the_content()` is returning null. This project uses Timber for most of the layout,although im avoiding rebuilding the entire WooCommerce layout so that I can still easily include 3rd party plugins on my projects.

The template in question is this:
```php
<?php
/**
 * Description tab
 *
 * @author 		WooThemes
 * @package 	WooCommerce/Templates
 * @version     2.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}

global $post;

$heading = esc_html( apply_filters( 'woocommerce_product_description_heading', __( 'Product Description', 'woocommerce' ) ) );

?>

<?php if ( $heading ): ?>
  <h2><?php echo $heading; ?></h2>
<?php endif; ?>

<?php the_content(); ?>
```

If I do a `var_dump`to the `global $post` var I do get the correct data, but `the_content` still outputs `NULL`.

Is there anything about Timber that could explain this? Im getting out of ideas of where to look for this problem :(

**Comment by hrsetyono** [comment]
Hi @lmartins, I just started a WooCommerce project and met this problem too. I followed [your guide](https://github.com/jarednova/timber/wiki/WooCommerce-Integration) and the Product Description is empty.

Of course I can remade the layout using `{{ post.content }}` but I want to keep the hook in case of 3rd party plugins.

Since you closed this issue, have you found the solution for this?

Thanks
