### ISSUE TITLE
How does this benefit me vs using the standard Twig autoloader?

### ISSUE THREAD

**Issue by webivation** [jarednova/timber#620]
Not really an issue I guess, but a clarification as I decide to move forward on a new development project... what does the do to benefit a developer over simply installing Twig and using it from the core Twig_Loader?

**Comment by christianmagill** [comment]
I'm also interested in this. Additionally, is it safe for production use, or are there a lot of breaking changes with plugin updates.

**Comment by jarednova** [comment]
Hi @webivation @christianmagill the big benefit of using Timber versus directly using the Twig auto loader is access to native WordPress items inside of an object that's prepared for Twig. For example, if you wanted to write a conditional based on the size of a post thumbnail...

### Timber
```twig
{% if post.thumbnail.width > 500 %}
    <img src="{{ post.thumbnail.src | resize(500} }}" alt="A resized thumbnail image for {{ post.title }}" />
{ % else %}
    <img src="{{ post.thumbnail.src }}" alt="A thumbnail for {{ post.title }}" />
{% endif %}
```

Could you do this all with PHP + Twig? Sure. But you'd basically be duplicating the work that's already been done here. 

In terms of production: Timber is being used in Production on [tons of sites](http://upstatement.com/timber#showcase). I'm very actively working on an official 1.0 release which will contain _some_ breaking changes; but these are focused on removing some functions/properties that have been deprecated for a long time. The 1.0 release isn't about any big new features, but cleaning up the code base so that the gunk is gone (and more thorough documentation exists) and you can feel better about using in production.

**Comment by christianmagill** [comment]
@jarednova Much thanks, looking forward to jumping in!
