### ISSUE TITLE
Execution of unprepared SQL statements

### ISSUE THREAD

**Issue by arall** [jarednova/timber#695]
Some queries seems to not being sanitised before it's execution.

In `wp-content/plugins/timber-library/lib/timber-archives.php` file, there are a bunch of calls to `$wpbd->get_results()` method, with a non sanitised query as parameter. Those are some examples:

```php
$query = "SELECT YEAR(post_date) AS `year`, count(ID) as posts FROM $wpdb->posts $join $where GROUP BY YEAR(post_date) ORDER BY post_date $order $limit";
// [...]
$results = $wpdb->get_results($query);
```

```php
$query = "SELECT YEAR(post_date) AS `year`, MONTH(post_date) AS `month`, count(ID) as posts "
. "FROM $wpdb->posts $join $where GROUP BY YEAR(post_date), MONTH(post_date) "
. "ORDER BY post_date $order $limit";
// [...]
$results = $wpdb->get_results($query);
```

```php
$query = "SELECT YEAR(post_date) AS `year`, MONTH(post_date) AS `month`, DAYOFMONTH(post_date) AS `dayofmonth`, count(ID) as posts FROM $wpdb->posts $join $where GROUP BY YEAR(post_date), MONTH(post_date), DAYOFMONTH(post_date) ORDER BY post_date $order $limit";
// [...]
$results = $wpdb->get_results($query);
```

**Comment by jarednova** [comment]
Hey @arall thanks for the heads-up on this. For the most part this is taken directly from WP Core's [`wp_get_archives` function](https://core.trac.wordpress.org/browser/tags/4.3.1/src/wp-includes/general-template.php#L1483). As you can see, they've got some other stuff going on for caching, etc. too -- but the same non-sanitized queries exist.

Can you show an example (or a PR!) of what these should look like instead?

**Comment by arall** [comment]
@jarednova In the `get_items` method, query arguments seems to be correctly sanitised, but in `get_items_monthly` and `get_items_yearly`, the parameters go directly to the query. However, those methods are only called from `get_items` method, after the sanitisation, so everything looks fine on those.

The `$join` and `$where` variables are generated using the `apply_filters` WP method, which is using `$post_type` and `$args` non-sanitised parameters, that come from outside. 
I'm not sure how safe is this. I will try to reproduce it later.

**Comment by arall** [comment]
Ok, this is actually injecting SQL:

```php
$args = ['post_type' => '" OR 1="1'];
$defaults = [
	'post_type' => 'post',
];
$args = wp_parse_args($args, $defaults);
$post_type = $args['post_type'];
$where = apply_filters('getarchives_where', 'WHERE post_type = "' . $post_type . '" AND post_status = "publish"', $args);
print_r($where);
```

**Comment by janjaap** [comment]
@jarednova Any news on this issue? To me, this issue seems more important than threaded comments...

**Comment by arall** [comment]
Any news on this guys? 
@rpkoller you were doing a PR for this. Can I help you with that?

**Comment by rpkoller** [comment]
Hi @arall . Yep I've worked a little on a PR. Simply wraped the queries into prepare statements. My main problem so far is that i was unable to get PHPUnit running to test if my changes would break anything cuz i don't really use the archive functionality in projects so nothing to test against on my local setup. Anyway I put some possible changes in here for discussion instead of place just a pull request. There are basically three areas: 

1) the queries inside the functions `get_itmes_monthly`and `get_items_yearly`

`get_items_yearly` in line 97

the initial query
```
$query = "SELECT YEAR(post_date) AS `year`, count(ID) as posts FROM $wpdb->posts $join $where GROUP BY YEAR(post_date) ORDER BY post_date $order $limit";
```
getting wrapped into prepare
```
$query = $wpdb->prepare("SELECT YEAR(post_date) AS `year`, count(ID) as posts FROM {$wpdb->posts} %s %s GROUP BY YEAR(post_date) ORDER BY post_date %s %s", $join, $where, $order, $limit);
```

`get_items_monthly` in line 135
the initial query
```
$query = "SELECT YEAR(post_date) AS `year`, MONTH(post_date) AS `month`, count(ID) as posts "
			. "FROM $wpdb->posts $join $where GROUP BY YEAR(post_date), MONTH(post_date) "
			. "ORDER BY post_date $order $limit";
```
getting wrapped into prepare
```
$query = $wpdb->prepare( "SELECT YEAR(post_date) AS `year`, MONTH(post_date) AS `month`, count(ID) as posts
			FROM {$wpdb->posts} %s %s GROUP BY YEAR(post_date), MONTH(post_date)
			ORDER BY post_date %s %d", $join, $where, $order, $limit );
```

2) the queries inside the `get_items` function 

The queries inside the get_items function you have mentioned are already properly sanatized. but maybe it would make sense to wrap them inside the prepare function anyway. the only problem is the type for each parameter isn't listed for the get_items function ( like string or int ) 

3) the queries inside `apply_filters`
The last one is the query inside the apply_filters function you have pointed out in one of your comments. Unsure if that would be the proper way and syntax but i would go like that: 

```
$where_query = $wpdb->prepare("WHERE post_type = %s AND post_status = `publish`", $post_type )
$where = apply_filters('getarchives_where', $where_query, $args);
```

**Comment by arall** [comment]
Hi @rpkoller.

Basically, `$wpdb->prepare` method will wrap with quotes all the parameters. So, for example, the `$join` and `$where` must be previously properly sanatized on it's creation process.

An example:
```php
$query = $wpdb->prepare("SELECT YEAR(post_date) AS `year`, count(ID) as posts FROM {$wpdb->posts} %s %s GROUP BY YEAR(post_date) ORDER BY post_date %s %s", 'LEFT JOIN ...', 'WHERE 1=1', 'DESC', 'LIMIT 10');
```
This will break the query, since will try to execute the following:
```sql
SELECT YEAR(post_date) AS `year`, count(ID) as posts FROM table 'LEFT JOIN ...' 'WHERE 1=1' GROUP BY YEAR(post_date) ORDER BY post_date 'DESC' 'LIMIT 10'
```
So the use of `$wpdb->prepare` doesn't fit in some cases.

**Comment by jarednova** [comment]
@arall check-out https://github.com/jarednova/timber/commit/a171a96fd3d4dde1618a26bfd3710e64db9761fa#diff-c7a63effa418bf82b4ced9467a5d6c26R229 and let me know if you think that resolves the issue. As both you and @rpkoller note, the `$join`, `$where`, etc. vars can't be prepared as this escapes the SQL. @Otto42 has more info on this WP Exchange post: http://wordpress.stackexchange.com/a/140318/71076

**Comment by arall** [comment]
It may work with the `$post_type`, but I don't see a proper fix for the `$join`and `$where` vars at https://github.com/jarednova/timber/commit/a171a96fd3d4dde1618a26bfd3710e64db9761fa#diff-c7a63effa418bf82b4ced9467a5d6c26R97

**Comment by Otto42** [comment]
That is not how prepare() works, and the suggested "fixes" above are totally incorrect.

Running an query directly is not dangerous unless there is a means for the query to be modified in an unsafe way.

**Comment by jarednova** [comment]
@Otto42 thanks so much for chiming-in and clearing that up. I'll confirm that the `$where` etc., are safely handled before closing this

**Comment by kvdnberg** [comment]
Any updates on this? This plugin is still considered unsafe to use in our PEN tests because of this issue.

**Comment by jarednova** [comment]
Hi @kvdnberg thanks for the nudge. After looking into this and the input we got from Otto42, I'm confident that there's no issue here.

Just because there's unprepared SQL does not mean it's inherently unsafe. The potential vulnerability exists if a user were to have access to PHP where they could somehow apply a filter to `getarchives_where` — which is something they can do WITHOUT Timber (this is a filter in WP Core). Besides, if someone has full PHP access they could call the ole' `global $wpdb` and wreck havoc anyway.
