### ISSUE TITLE
Enqueue scripts the right way

### ISSUE THREAD

**Issue by petenorris** [jarednova/timber#750]
HI all,
I have the functions.php file from the timber starter theme and was wondering the best way to enqueue my styles? An example would be awesome as my PHP is pretty much in the realms of copy paste. Many thanks.

**Comment by dinolatoga** [comment]
This isn't the best way but sometimes I do it like this. Hope this helps.

````
<?php

if ( ! class_exists( 'Timber' ) ) {
	add_action( 'admin_notices', function() {
			echo '<div class="error"><p>Timber not activated. Make sure you activate the plugin in <a href="' . esc_url( admin_url( 'plugins.php#timber' ) ) . '">' . esc_url( admin_url( 'plugins.php' ) ) . '</a></p></div>';
		} );
	return;
}

Timber::$dirname = array('templates', 'views');

class StarterSite extends TimberSite {

	function __construct() {
		add_theme_support( 'post-formats' );
		add_theme_support( 'post-thumbnails' );
		add_theme_support( 'menus' );
		add_filter( 'timber_context', array( $this, 'add_to_context' ) );
		add_filter( 'get_twig', array( $this, 'add_to_twig' ) );
		add_action( 'init', array( $this, 'register_post_types' ) );
		add_action( 'init', array( $this, 'register_taxonomies' ) );
		add_action( 'wp_enqueue_scripts', array( $this, 'loadScripts' ) );
		parent::__construct();
	}

	function register_post_types() {
		//this is where you can register custom post types
	}

	function register_taxonomies() {
		//this is where you can register custom taxonomies
	}

	function add_to_context( $context ) {
		$context['foo'] = 'bar';
		$context['stuff'] = 'I am a value set in your functions.php file';
		$context['notes'] = 'These values are available everytime you call Timber::get_context();';
		$context['menu'] = new TimberMenu();
		$context['site'] = $this;
		return $context;
	}

	function add_to_twig( $twig ) {
		/* this is where you can add your own fuctions to twig */
		$twig->addExtension( new Twig_Extension_StringLoader() );
		$twig->addFilter( 'myfoo', new Twig_Filter_Function( 'myfoo' ) );
		return $twig;
	}

	function loadScripts() {
		wp_enqueue_script( 'script-name', get_template_directory_uri() . '/js/example.js', array(), '1.0.0', true );
	} 

}

new StarterSite();

function myfoo( $text ) {
	$text .= ' bar!';
	return $text;
}
````

**Comment by petenorris** [comment]
Thanks, that seems to do the trick.

**Comment by infn8** [comment]
You can also register enqueue scripts in the 100% regular old WP way.  The example above works, not because of some twig magic, but because calling 
```php
add_action( 'wp_enqueue_scripts', array( $this, 'loadScripts' ) );
``` 
in the ```__construct``` function is just another example of a php line that always runs.  you could also just drop 
```php
add_action( 'wp_enqueue_scripts', 'myLoadScripts' );
``` 
in the basic body of ```functions.php``` and then just call your function ```myLoadScripts``` and be done with it. 

For the record the way above *is* cleaner it's just worth noting what's actually happening here.

One thing I like to do is to **register** scripts and styles for different blocks and page templates, Then i only **enqueue** them on pages that actually use those template or components.  in THAT case you may want to do the enqueue from a twig file.  in that case you want to extend twig with a custom FN like this:
```php
<?php 
function add_to_twig( $twig ) {
	/* this is where you can add your own fuctions to twig */
	$twig->addFunction($function);
	$function = new Twig_SimpleFunction('enqueue_script', function ($handle) {
		// register it elsewhere
		wp_enqueue_script( $handle);
	});
	$twig->addFunction($function);
	$function = new Twig_SimpleFunction('enqueue_style', function ($handle) {
		// register it elsewhere
		wp_enqueue_style( $handle);
	});
	$twig->addFunction($function);
	return $twig;
}
?>
```

then you can call in your twig file
```twig
{{ enqueue_script('handle') }}
```
and you will get that script enqueued for the footer.  just make sure you're calling:
```twig
{{ function('wp_footer') }}
```
somewhere in ```base.twig``` just before the ```</body>```

**Comment by landsman** [comment]
Can you add this to documentation as the right way please?

**Comment by oppenheimer-** [comment]
Sorry to bring this issue up again, @infn8 
I find your solution to be very helpful in a component based approach.

What I'm struggling with is that every script and style goes into the footer. I think this is because the custom functions to enqueue styles/scripts are called way too late to get them into the head of the page.

Did you just go with CSS in the footer or is there any workaround to circumvent this very situation?
Thanks for any idea on this!

**Comment by xzykho** [comment]
I just wanted to add and not really sure if this is the right way to do it re: @oppenheimer issue. I went to the html-header.twig then 

`<link rel="stylesheet" href="{{ add_style() }}" type="text/css" media="screen" />`

after adding this to my functions.php

`$twig->addFunction(new Timber\Twig_Function('add_style', function () {
            echo get_template_directory_uri() . '/dist/app.css';
            wp_register_style('style', get_template_directory_uri() . '/dist/app.css', [], '1', 'all');
            wp_enqueue_style('style');
}));`

**Comment by pjoulot** [comment]
Hi, I used that method to include my style sheets only when needed. It works perfectly for the frontend, but the style sheets are not loaded when using Gutenberg, that's so sad.
