### ISSUE TITLE
is there a way to regenate all image sizes.?

### ISSUE THREAD

**Issue by koraysels** [jarednova/timber#754]
HI I want to rebuild all images.. some sizes are no longer being used and take up a large amount of disk space. also I would like to be able to regenerate all sizes.. is that possible ?

I know of a plugin which does this for wordpress but not sure if it will work with timber's take on resizing images ?

thanks

**Comment by t-wright** [comment]
Hi there,
The resized images are only generated the first time the size is requested for that image... so you can simply delete the resized images (don't delete the original, uploaded images) and they'll be regenerated at the new size when the page is accessed.

**Comment by lmartins** [comment]
You can also use something like:
https://wordpress.org/plugins/regenerate-thumbnails/

**Comment by koraysels** [comment]
hi @lmartins regenerate thumbnails will not work with timber right ? it is seperate from wordpress image sizes or am I wrong ?

**Comment by lgaechter** [comment]
If you use the [resize filter](https://github.com/jarednova/timber/wiki/TimberImage#resize) in your twig files, then Regenerate Thumbnails will not work, because it only regenerates image sizes defined in Settings &rarr; Media or additional image sizes added with `add_image_size`.

If you **use Timber without the resize filter**, then **Regenerate Thumbnails will work** for you.

**Comment by koraysels** [comment]
yeah but ofcourse i use the epic resize filter for all my responsive image needs.. :(

**Comment by connorjburton** [comment]
Hi @koraysels did you ever find a solution for this, what about deleting the resized files? If not this is something we may need to look at.

**Comment by koraysels** [comment]
No i did not find a solution.. it is still eating up my harddrive everytime i change the resize parameters when i am working on responsive images. I think it would be a great funtionality to make Timber even better! Also a way of setting the compression quality would be really cool!

**Comment by connorjburton** [comment]
Okay, thanks for replying. I'll put this on my list to look at.

Interesting you mentioned setting compression as we had a discussion on #857 regarding that, may be of interest.

**Comment by lgaechter** [comment]
I have some kind of solution, I think, but it requires handling images in your theme a little differently.

Timber doesn’t really know which image sizes you use, so it cannot tell which files it has to delete. Analyzing twig files and read what values you put in the resize filter wouldn’t make any sense, either. 

**What if we defined image sizes in a way that Timber always knows all sizes you will use?**

We recently ran into a related problem. We had posts that were created automatically when real estate data was imported into WordPress with a plugin we wrote ourselves. Together with these posts, a lot of images were also pulled in. Because we work with Timber, all the image sizes would only be generated if someone would access the frontend of a real estate post, which could mean very long loading times for the first visitor. This is not cool if you have also have an image gallery on the page.
So we arrived at the same point: Timber needs to know image sizes beforehand in order to be able to generate sizes when images are uploaded.

We came up with **Timmy**, an opt-in plugin for Timber that we just put on GitHub: https://github.com/MINDKomm/Timmy.

The idea is that you define your image sizes centrally in your theme and get a lot of benefits through Timmy, which works on top of Timber. Among other features which you can read about in the plugin Readme, it would also solve your problem of too many generated images that now lie in your uploads folder:

* **With Timmy you can use Regenerate Thumbnails**. It will delete all image sizes generated with Timber and then regenerate all the sizes you defined with Timmy. In the end, you will end up with a clean uploads folder that contains only image sizes you actually use on your site.

For you this would mean that you would make all image size changes in one place: the [image configuration](https://github.com/MINDKomm/Timmy#image-configuration), which is just a function that you add to `functions.php` of your theme.

Here’s an example:
```php
function get_image_sizes() {
    return array(
        'thumbnail' => array(
            'resize' => array( 150, 150 ),
            'name' => 'Thumbnail',
            'post_types' => array( 'all' ),
        ),
        'custom-4' => array(
            'resize' => array( 370 ),
            'srcset' => array( 2 ),
            'size' => '(min-width: 992px) 33.333vw, 100vw',
            'name' => 'Width 1/4',
            'post_types' => array( 'post', 'page' ),
        ),
    );
}
```

---

I don’t know if it would be a good idea to incorporate this idea into Timber itself. We have already used Timmy in some projects and for us it worked really well. Especially the responsive image markup generation is basically [what was introduced](https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/) into WordPress Core in version 4.4.

**Comment by connorjburton** [comment]
Hey @igaechter, this concept seems great. I'll take a look at this in a couple of days but it seems to solve a bunch of problems.

May be the start of an advanced image extension @jarednova?

**Comment by connorjburton** [comment]
Closing this as @gchtr seems to have provided the best solution for the near future.
