### ISSUE TITLE
how to display an archive of authors and then the author details page?

### ISSUE THREAD

**Issue by beatelite** [jarednova/timber#806]
Hi, forgive me for the dumb question but I'm new to timber and am trying to determine the best way to do the following:

1) display a list of authors
2) when someone clicks on their name/avatar, it takes them to the author's bio page. 

I thought I could just create a author.php file - call the timber getuser method and then use the data in the author.twig file but that's not really working out - or I'm doing it wrong. 

Couldn't find anything in the guides. Have any recommendations?

**Comment by beatelite** [comment]
For the author detail's page, here's what I'm trying:

author.php
```
<?php
$context['current_user'] = new TimberUser();
$context['post'] = new TimberPost();
Timber::render('author.twig', $context);
```

author.twig
```
<p class="current-user-info">Your name is {{ current_user.name }}</p>
```

When I visit the author/username I get a blankpage. 

I am using the timber starter theme and timber is active.

**Comment by beatelite** [comment]
Ok, I figured it out. I was calling the wrong template path. In needed to add in templates/author.twig. I can now get all data from the current author by using these from the starter theme: https://github.com/Upstatement/timber-starter-theme/blob/d16e6bf43a2351357bb5ed5f3c0348e71a048397/templates/author.twig
https://github.com/Upstatement/timber-starter-theme/blob/d16e6bf43a2351357bb5ed5f3c0348e71a048397/author.php

closing out.

**Comment by prob2424** [comment]
I am also wishing to just render a list of authors on the site. My solution is like yours above but the problem I'm having is the loop targets all the posts - which means my display is showing the same author repeated on the list for each of their posts - a duplicates situation - rather than just presenting the author once.  I don't think Twig would be used to ignore duplicates simply? I would have to do it in the PHP? Any thoughts here are helpful. Thanks.

**Comment by beatelite** [comment]
Can you give me an example of your code?

**Comment by prob2424** [comment]
I've outlined below - author-archive.php > author-archive.twig > front-page.twig  -  Keeping in mind my return provides the info I wish, (author avatar and author name linking to their page) but it's looping through each post and rendering duplicates of the same author names/avatars for each respective post they wrote. I assume this is a scope thing - I've tried to say {% for author in authors %} for example, but I get no data to render. Thank you for looking!

author-archive.php:

`<?php
/**

 * @package  WordPress
 * @subpackage  Timber
 * @since    Timber 0.1
 */
 $reviews = array(
 		'post_type' => 'reviews',    
 			);

global $wp_query;

$context = Timber::get_context();
$context['reviews'] = Timber::get_posts($reviews);
$context['posts'] = Timber::get_posts();
$context['users'] = Timber::get_users();
$context['authors'] = Timber::get_users();
if ( isset( $wp_query->query_vars['author'] ) ) {
	$author = new TimberUser( $wp_query->query_vars['author'] );
	$context['author'] = $author;
	$context['title'] = $author->nickname();
  $context['title'] = 'Author Archives: ' . $author->nickname();

}
Timber::render( array( 'author-archive.twig'), $context );`


author-archive.twig

`<div class="rooms_surround"><article class="tease archive author author-{{ post.author.nickname }} author-{{post.author.id}}"id="tease-"><a href="{{post.author.path}}"><div class="reviews_summary_image" style="background-image:url('{{(post.author.avatar)}}'); background-size: contain; background-position: center; background-repeat:no-repeat;"></div></a><div class="reviews_summary_content"><h2><a href="{{post.author.path}}"> {{ post.author.nickname }} </a></h2></div></article></div>`



front-page.twig:

`{% extends "base-home.twig" %}

{% block rooms %}
	{% for post in posts %}
		{% include ["author-archive.twig"] %}
{% endfor %}
{% endblock %}`

**Comment by prob2424** [comment]
Let me know if the above code isn't useful. Thank you!
