### ISSUE TITLE
TimberImage resize, files with uppercase extensions are being uploaded multiple times

### ISSUE THREAD

**Issue by hbrok** [jarednova/timber#829]
I'm using TimberImage to resize images from external URLs, some of these images have uppercase file extensions (like .JPG). However, a new copy of the same image is being uploaded every time the page with the resize function is loaded.

I think this is due to the fact that when a file is saved, it's saved with a lowercase extension  and `TimberImageHelper::get_sideloaded_file_loc(...)` is returning a string with an uppercase extension that's being compared to the lowercase extension in `TimberImageHelper::sideload_image(...)`.

If that's the case, I think adding `strtolower` on [line 274](https://github.com/jarednova/timber/blob/master/lib/timber-image-helper.php#L274) would fix it:

```php
$ext = strtolower( $path_parts['extension'] );
```
In the meantime I'm using `{{ post.image|lower|resize(845, 425) }}` which is working for now.

**Comment by connorjburton** [comment]
Hi @hbrok, I have tried to replicate this on a local installation but I can't seem to get it to happen, I have an external image such as:

```php
{{TimberImage('http://local.website.co.uk/hest.JPG')|resize(300,600)}}
```

And it will generate something like

`42123710cb0cd8c9edba9ca4b6210f72-300x600-c-default.jpg`

It will reference `42123710cb0cd8c9edba9ca4b6210f72-300x600-c-default.JPG` in the `.twig` file, rather than `.jpg` which I guess is an issue but it doesn't seem to regenerate the file every time.

Do you have any more info on this?

**Comment by hbrok** [comment]
Hey @connorjburton, thanks for looking into this!

Testing locally gives me the same result as you (no duplicated files, but a reference to the uppercase extension), but testing it on a different site on my server gives me the same image duplication issue.

I know my filesystem isn't case sensitive, so I have a suspicion that may be why it's not able to be reproduced locally.

**Comment by connorjburton** [comment]
Okay, well I think this is still an issue so will set it to be fixed

**Comment by haroldangenent** [comment]
I am (still) experiencing the same issues as @hbrok on 1.0.5 (installed from WPackagist). Files do work and get served through lowercase `.jpg`, but are downloaded _every time_ the page loads (or the function is called). In no time, the server contains hundreds of (the same) files. I also only experienced this on some servers (for example, not on my local Vagrantbox).

Boiled it down to this part of `Timber\ImageHelper`:
```
$loc = self::get_sideloaded_file_loc($file);
if ( file_exists($loc) ) {
    return URLHelper::preslashit(URLHelper::get_rel_path($loc));
}
```

The file never exists when `.JPG` is used. Therefore, the function continues to download the file. The new filename becomes `file-1.JPG`.

**"Some" servers**
This seems to have something to do with case sensitivity of some file systems. `file_exists` returns `true` on my Vagrant box, but not on some other servers.

**Possible solution**
The method `get_sideloaded_file_loc` determines the extension of the image like this:

```
$ext = 'jpg';
if ( isset($path_parts['extension']) ) {
    $ext = $path_parts['extension'];
}
```

This should probably be lowercased using `strtolower()`. I'm not sure why and where all files are _saved_ with lowercase initially though.

**Comment by haroldangenent** [comment]
@connorjburton Maybe this should be reopened, since the effect of this issue has quite a high impact (images are downloaded *each page view*). If you'd like me to file another issue, let me know.

For anyone looking for a (hacky) workaround, see https://github.com/timber/timber/issues/1098#issuecomment-233343459.
