### ISSUE TITLE
[question] Timber with REST-API in Wordpress 4.4

### ISSUE THREAD

**Issue by eshimischi** [jarednova/timber#830]
Hi. Very interesting how to use Timber with REST-API in Wordpress 4.4?

**Comment by beatelite** [comment]
What are you trying to achieve? Maybe I can help. i currently use both.

**Comment by eshimischi** [comment]
Maybe you can show simple examples of using it both together?

**Comment by beatelite** [comment]
Well, that's tough because I wouldn't use them together, personally. Timber has it's own way of getting wp data. The api is just another way. I suppose you could set something up where timber was getting the json data from the api. But then, why do that when timber can already do that. 

I personally use angularjs as a custom admin to perform admin tasks on the data (get, put,post delete) and then use timber for ease of display on the frontend. I don't really mix the two because, personally, I don't see the need but it could differ for someone else. Do you have a specific case in mind?

**Comment by eshimischi** [comment]
I'm personally use React for the same things and isomorphic fetch to get the data, but question was about Timber and Rest API combing and without any sugar like Angular or React, to became too fat to use much frameworks or APIs to do a simple things and etc. I thought that someone really did something together, just for example.

**Comment by nickmoline** [comment]
The point is there's no actual reason to use the REST-API from Timber because Timber has direct access to the database and the models using the functionality.  Adding REST calls to, for example, fetch the contents of post 45, would be adding HTTP round trips to an API which would end up doing the exact same Database queries that you could do directly using 

```php
$post45 = new TimberPost(45);
```

You would be adding unnecessary TCP overhead to something that already is slower than would be ideal, so why do it.

Use of the REST API in the frontend is primarily useful if you want to build a frontend that is outside the context of Wordpress, or if you want to change the content of your frontend after pages load with javascript access to the backend (using something like Angular or React or just plain AJAX calls)

**Comment by eshimischi** [comment]
@nickmoline i see, thanks for your answer!

**Comment by nickmoline** [comment]
No problem @eshimischi, if you really want to do it, I could write up a sample of using curl to make API calls to the REST API (it certainly IS possible, just not practical unless you have some sort of specific use case that using the REST API would make more sense than direct DB calls).

**Comment by eshimischi** [comment]
@nickmoline there is n o need, thank you. just digged thru the google https://github.com/kadamwhite/wordpress-rest-api

**Comment by corysimmons** [comment]
@nickmoline I'd be interested in those examples.

I think the benefit of using WP REST API is to generate an API that can be used in multiple contexts. For instance, I might want to use Timber for templating on desktop, but might also want to make an Apple Watch app that uses some JS framework.

Would Timber even be useful in this context? Or, at that point, are we just talking about Twig?

If the latter, I'll take examples for that too. :}

**Comment by nickmoline** [comment]
@corysimmons your Apple Watch app (or mobile app, or progressive javascript web app, or whatever) wouldn't be going through Timber at all but instead would be speaking directly to the REST API.

The bottom line is that Timber, and the REST API serve different (complimentary) purposes.  Timber does not need the REST API itself because it is a template and is just templating out the data that is already available to it through WP's theming engine.  If you are wanting to speak via Javascript or REST, this is something that happens outside of the context of theming display.

One very likely scenario is that you'd create a progressive web app where the basic layout and initial content is themed with twig through timber, and then after the page loads javascript speaks directly to the REST API to alter the content of the displayed page.

If you try to make Timber load its data from the REST API, you have artificially added slowness that your application doesn't need because you are adding an HTTP call to fetch data when the data is already available.

If you are making javascript to talk to the REST API after the page loads, well that's just javascript, timber is no longer involved at that point.

Both the REST API and Timber serve the purpose of fetching and rendering data, but at a different point in the stack.
